### ISSUE TITLE
sdir converter

### ISSUE THREAD

**Issue by jzhoulon** [spcl/mlir-dace#21]
Hi, developers, 
I saw https://mlir.llvm.org/OpenMeetings/2022-01-2001~Data-Centric-Model.pdf , it seems that there is a converter to convert mlir generated by polygeist to SDIR, but I didn't find it in mlir-dace, seems mlir-dace only provides sdir-opt and sdir-translate, is there a place  where I can find that mlir(arith, scf) to sdir's converter? thanks

**Comment by Berke-Ates** [comment]
Hey!
If you checkout the branch `to-sdir-converter` and build it then you'll have a `sdfg-opt --convert-to-sdfg`, which you can use to convert a subset of the Arith, Memref, Math and SCF dialects to the SDFG dialect. The branch should be merged into main soon.
